package com.lu.warehouse.settings.domain;

public class PmsUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_user.user_id
     *
     * @mbggenerated Tue Sep 20 12:59:13 CST 2022
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_user.user_name
     *
     * @mbggenerated Tue Sep 20 12:59:13 CST 2022
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_user.user_pwd
     *
     * @mbggenerated Tue Sep 20 12:59:13 CST 2022
     */
    private String userPwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_user.user_id
     *
     * @return the value of pms_user.user_id
     *
     * @mbggenerated Tue Sep 20 12:59:13 CST 2022
     */

    private Long userPerm;

    public Long getUserPerm() {
        return userPerm;
    }

    public void setUserPerm(Long userPerm) {
        this.userPerm = userPerm;
    }

    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_user.user_id
     *
     * @param userId the value for pms_user.user_id
     *
     * @mbggenerated Tue Sep 20 12:59:13 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_user.user_name
     *
     * @return the value of pms_user.user_name
     *
     * @mbggenerated Tue Sep 20 12:59:13 CST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_user.user_name
     *
     * @param userName the value for pms_user.user_name
     *
     * @mbggenerated Tue Sep 20 12:59:13 CST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_user.user_pwd
     *
     * @return the value of pms_user.user_pwd
     *
     * @mbggenerated Tue Sep 20 12:59:13 CST 2022
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_user.user_pwd
     *
     * @param userPwd the value for pms_user.user_pwd
     *
     * @mbggenerated Tue Sep 20 12:59:13 CST 2022
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }
}