package com.lu.warehouse.settings.mapper;

import com.lu.warehouse.settings.domain.PmsUser;
import org.mybatis.spring.annotation.MapperScan;

import java.util.Map;

public interface PmsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated Tue Sep 20 12:59:13 CST 2022
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated Tue Sep 20 12:59:13 CST 2022
     */
    int insert(PmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated Tue Sep 20 12:59:13 CST 2022
     */
    int insertSelective(PmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated Tue Sep 20 12:59:13 CST 2022
     */
    PmsUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated Tue Sep 20 12:59:13 CST 2022
     */
    int updateByPrimaryKeySelective(PmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_user
     *
     * @mbggenerated Tue Sep 20 12:59:13 CST 2022
     */
    int updateByPrimaryKey(PmsUser record);

    /**
     * 根据账号和密码查数据
     * @param map
     * @return
     */
    PmsUser selectUserByUserIdAndPwd(Map<String,Object> map);

    String selectPasswordById(String userName);

    Long selectUserIdByName(String userName);

    Long selectPermByName(String userName);
}